### ISSUE TITLE
Kubed shows abnormal high I/O and memory usage

### ISSUE THREAD

**Issue by MXClyde** [appscode/kubed#357]
We use Kubed for a small task: synchronizing two SSL certificate secrets to 25 namespaces.

This ran fine for months, but over the past 4-6 weeks we saw  see cluster nodes become unavailable for scheduling as a result of connectivity problems from the kubelet towards the Docker engine, so called PLEG issues (https://github.com/kubernetes/kubernetes/issues/45419).

After further analysis, it became apparant that the affected nodes were running kubed. By using iotop, we found out that kubed was writing to disk at a sustained speed of up to 1-1,5 MB/s continously:

[
![ioaws](https://user-images.githubusercontent.com/15819650/59858524-6c5ff800-937b-11e9-9ace-6ccd60609c97.gif)
](url)

At the same time the kubed container grew to memory usage of > 2 GB.

Restarting the container immediately results in the above levels of I/O usage and the container grows to several hundred megabytes of memory usage within minutes.

This behaviour is observed both on kubed 0.9 and 0.10. As a result, we have disabled kubed for now. This normalizes the situation.

The whole kubed configuration was working fine until several weeks ago. 
Please find the profiler output attached.

Any idea how to remedy this situation?
[allocs.txt](https://github.com/appscode/kubed/files/3310952/allocs.txt)
[goroutine.txt](https://github.com/appscode/kubed/files/3310953/goroutine.txt)
[heap.txt](https://github.com/appscode/kubed/files/3310954/heap.txt)
[threadcreate.txt](https://github.com/appscode/kubed/files/3310955/threadcreate.txt)

**Comment by MXClyde** [comment]
I have also seen this happening now in two other clusters running in another cloud. This happens both on AWS EKS and Azure AKS. Any idea where to get started with isolating this?

**Comment by discostur** [comment]
having the same problem with the high load - kubed shows some nil pointer errors:

```
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc0007beab0, 0xc000934790, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc00026a870, 0x63ad840, 0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
I0703 06:43:55.000407       1 log.go:172] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 243372 [running]:
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00026a870)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc0007beab0, 0xc000b2a790, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc00026a870, 0x63ad840, 0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
I0703 07:43:55.000336       1 log.go:172] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 259452 [running]:
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00026a870)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc0007beab0, 0xc000c09790, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc00026a870, 0x63ad840, 0xc00050c440)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
```

**Comment by discostur** [comment]
@tamalsaha any news on this?

**Comment by scottrigby** [comment]
This seems to be a duplicate of #304? Also see #361

**Comment by tamalsaha** [comment]
I would like to hear your feedback on https://github.com/appscode/kubed/issues/304#issuecomment-521369891 .

**Comment by MXClyde** [comment]
News on this?

**Comment by tamalsaha** [comment]
I have released v0.11.0 https://github.com/appscode/kubed/releases/tag/v0.11.0 . Please give it a shot.

**Comment by MXClyde** [comment]
Have been running it in 2 clustrers, one of them for a few hours. Looks good until now.

**Comment by MXClyde** [comment]
After three days:
- One cluster looks fine: kubed container has grown to 728 MB), no abornmal I/O
- The other cluster remains problematic: kubed container grown to 3.2Gb, abnormal high I/O usage)
In both clusters kube is only used to simply replicate an SSL certificate in a secret to other namespaces.
Is there anything I can provide to help troubleshooting?

**Comment by discostur** [comment]
Just installed v0.11 in one of our clusters and we still see the extremly high IO usage of kubed. Memory is still growing, but i only started it 10 minutes ago ... will update this tomorrow.

Just syncing secrets / configmaps across namespaces. Cluster has 19 namespaces and 5 nodes ...

**Comment by mbelang** [comment]
I have this as well. There are spikes of I/O when it writes ConfigMaps to namespace but sometimes it start doing steady I/O writes and the CPU iowait on the node `kubed` is running on bump up to 60% making the node barely usable.

![kubed-io-writes](https://user-images.githubusercontent.com/5888932/65065910-5a2d3000-d951-11e9-8736-0feaf22846c0.png)

The memory is caped to the limit I set so I suspect that it is doing swap but this is not normal. Buming the memory limit to 512MB has the same behavior.

**Comment by phpai** [comment]
Same behaviour on our cluster. We are using kubed v0.11 to sync secrets/configmaps to namespaces.

Running AKS v1.13.10, with 5 nodes and between 50 and 60 namespaces that kubed is syncing to. Will be updating to 1.14.x soon, to check if high usage of memory also occurs in k8s 1.14.x

<img width="1830" alt="Bildschirmfoto 2019-09-23 um 16 08 31" src="https://user-images.githubusercontent.com/20185479/65433766-eb067e80-de1d-11e9-8dfc-a91c917e754c.png">

Output on startup, after that no errors, just info that secrets/cm are syncing to namespaces

```
I0923 11:41:57.182189       1 log.go:172] FLAG: --alsologtostderr="false"
I0923 11:41:57.182714       1 log.go:172] FLAG: --audit-dynamic-configuration="false"
I0923 11:41:57.182804       1 log.go:172] FLAG: --audit-log-batch-buffer-size="10000"
I0923 11:41:57.182879       1 log.go:172] FLAG: --audit-log-batch-max-size="1"
I0923 11:41:57.183696       1 log.go:172] FLAG: --audit-log-batch-max-wait="0s"
I0923 11:41:57.183728       1 log.go:172] FLAG: --audit-log-batch-throttle-burst="0"
I0923 11:41:57.183735       1 log.go:172] FLAG: --audit-log-batch-throttle-enable="false"
I0923 11:41:57.183749       1 log.go:172] FLAG: --audit-log-batch-throttle-qps="0"
I0923 11:41:57.183755       1 log.go:172] FLAG: --audit-log-format="json"
I0923 11:41:57.183777       1 log.go:172] FLAG: --audit-log-maxage="0"
I0923 11:41:57.183787       1 log.go:172] FLAG: --audit-log-maxbackup="0"
I0923 11:41:57.183855       1 log.go:172] FLAG: --audit-log-maxsize="0"
I0923 11:41:57.183862       1 log.go:172] FLAG: --audit-log-mode="blocking"
I0923 11:41:57.183867       1 log.go:172] FLAG: --audit-log-path="-"
I0923 11:41:57.183877       1 log.go:172] FLAG: --audit-log-truncate-enabled="false"
I0923 11:41:57.183883       1 log.go:172] FLAG: --audit-log-truncate-max-batch-size="10485760"
I0923 11:41:57.183919       1 log.go:172] FLAG: --audit-log-truncate-max-event-size="102400"
I0923 11:41:57.183931       1 log.go:172] FLAG: --audit-log-version="audit.k8s.io/v1"
I0923 11:41:57.183936       1 log.go:172] FLAG: --audit-policy-file=""
I0923 11:41:57.183942       1 log.go:172] FLAG: --audit-webhook-batch-buffer-size="10000"
I0923 11:41:57.183951       1 log.go:172] FLAG: --audit-webhook-batch-initial-backoff="10s"
I0923 11:41:57.183957       1 log.go:172] FLAG: --audit-webhook-batch-max-size="400"
I0923 11:41:57.183962       1 log.go:172] FLAG: --audit-webhook-batch-max-wait="30s"
I0923 11:41:57.183967       1 log.go:172] FLAG: --audit-webhook-batch-throttle-burst="15"
I0923 11:41:57.183976       1 log.go:172] FLAG: --audit-webhook-batch-throttle-enable="true"
I0923 11:41:57.183982       1 log.go:172] FLAG: --audit-webhook-batch-throttle-qps="10"
I0923 11:41:57.183987       1 log.go:172] FLAG: --audit-webhook-config-file=""
I0923 11:41:57.183996       1 log.go:172] FLAG: --audit-webhook-initial-backoff="10s"
I0923 11:41:57.184001       1 log.go:172] FLAG: --audit-webhook-mode="batch"
I0923 11:41:57.184006       1 log.go:172] FLAG: --audit-webhook-truncate-enabled="false"
I0923 11:41:57.184015       1 log.go:172] FLAG: --audit-webhook-truncate-max-batch-size="10485760"
I0923 11:41:57.184021       1 log.go:172] FLAG: --audit-webhook-truncate-max-event-size="102400"
I0923 11:41:57.184026       1 log.go:172] FLAG: --audit-webhook-version="audit.k8s.io/v1"
I0923 11:41:57.184031       1 log.go:172] FLAG: --authentication-kubeconfig=""
I0923 11:41:57.184040       1 log.go:172] FLAG: --authentication-skip-lookup="false"
I0923 11:41:57.184046       1 log.go:172] FLAG: --authentication-token-webhook-cache-ttl="***REDACTED***"
I0923 11:41:57.184051       1 log.go:172] FLAG: --authentication-tolerate-lookup-failure="false"
I0923 11:41:57.184064       1 log.go:172] FLAG: --authorization-always-allow-paths="[]"
I0923 11:41:57.184101       1 log.go:172] FLAG: --authorization-kubeconfig=""
I0923 11:41:57.184123       1 log.go:172] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I0923 11:41:57.184138       1 log.go:172] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I0923 11:41:57.184149       1 log.go:172] FLAG: --bind-address="0.0.0.0"
I0923 11:41:57.184171       1 log.go:172] FLAG: --burst="1000000"
I0923 11:41:57.184177       1 log.go:172] FLAG: --cert-dir="apiserver.local.config/certificates"
I0923 11:41:57.184185       1 log.go:172] FLAG: --client-ca-file=""
I0923 11:41:57.184233       1 log.go:172] FLAG: --clusterconfig="/srv/kubed/config.yaml"
I0923 11:41:57.184262       1 log.go:172] FLAG: --contention-profiling="false"
I0923 11:41:57.184272       1 log.go:172] FLAG: --enable-analytics="true"
I0923 11:41:57.184277       1 log.go:172] FLAG: --enable-swagger-ui="false"
I0923 11:41:57.184281       1 log.go:172] FLAG: --help="false"
I0923 11:41:57.184288       1 log.go:172] FLAG: --http2-max-streams-per-connection="1000"
I0923 11:41:57.184296       1 log.go:172] FLAG: --kubeconfig=""
I0923 11:41:57.184302       1 log.go:172] FLAG: --log-flush-frequency="5s"
I0923 11:41:57.184308       1 log.go:172] FLAG: --log_backtrace_at=":0"
I0923 11:41:57.184322       1 log.go:172] FLAG: --log_dir=""
I0923 11:41:57.184398       1 log.go:172] FLAG: --logtostderr="false"
I0923 11:41:57.184436       1 log.go:172] FLAG: --profiling="true"
I0923 11:41:57.184448       1 log.go:172] FLAG: --qps="1e+06"
I0923 11:41:57.184456       1 log.go:172] FLAG: --requestheader-allowed-names="[]"
I0923 11:41:57.184460       1 log.go:172] FLAG: --requestheader-client-ca-file=""
I0923 11:41:57.184467       1 log.go:172] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0923 11:41:57.184480       1 log.go:172] FLAG: --requestheader-group-headers="[x-remote-group]"
I0923 11:41:57.184486       1 log.go:172] FLAG: --requestheader-username-headers="[x-remote-user]"
I0923 11:41:57.184496       1 log.go:172] FLAG: --resync-period="10m0s"
I0923 11:41:57.184501       1 log.go:172] FLAG: --scratch-dir="/tmp"
I0923 11:41:57.184505       1 log.go:172] FLAG: --secure-port="8443"
I0923 11:41:57.184510       1 log.go:172] FLAG: --stderrthreshold="0"
I0923 11:41:57.184515       1 log.go:172] FLAG: --tls-cert-file="/var/serving-cert/tls.crt"
I0923 11:41:57.184523       1 log.go:172] FLAG: --tls-cipher-suites="[]"
I0923 11:41:57.184543       1 log.go:172] FLAG: --tls-min-version=""
I0923 11:41:57.184548       1 log.go:172] FLAG: --tls-private-key-file="/var/serving-cert/tls.key"
I0923 11:41:57.184553       1 log.go:172] FLAG: --tls-sni-cert-key="[]"
I0923 11:41:57.184557       1 log.go:172] FLAG: --use-kubeapiserver-fqdn-for-aks="true"
I0923 11:41:57.184562       1 log.go:172] FLAG: --v="3"
I0923 11:41:57.184566       1 log.go:172] FLAG: --vmodule=""
I0923 11:41:57.268694       1 run.go:26] Starting kubed...
I0923 11:41:58.123035       1 client_config.go:104] resetting Kubeconfig host to [redacted] for AKS to workaround https://github.com/Azure/AKS/issues/522
I0923 11:41:58.126396       1 lib.go:112] Kubernetes version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
I0923 11:41:58.170044       1 operator.go:100] configuring kubed ...
E0923 11:41:58.276006       1 restmapper.go:117] Skipping failed API Groups: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
I0923 11:41:58.813907       1 operator.go:100] configuring kubed ...
E0923 11:41:58.956259       1 restmapper.go:117] Skipping failed API Groups: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
I0923 11:41:58.957509       1 secure_serving.go:116] Serving securely on [::]:8443
```

**Comment by mbelang** [comment]
isn't that an error `E0923 11:41:58.956259       1 restmapper.go:117] Skipping failed API Groups: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request` @phpai ?

**Comment by phpai** [comment]
Yes, getting same error as you mentioned in your post above. Maybe i phrased in incorrectly. What i meant is besides this error on startup, no other could be errors visible in the logs.

**Comment by mbelang** [comment]
@tamalsaha any news on this. kubed is still leaking and causing problems. Have you discovered something? Thank you

**Comment by estahn** [comment]
![image](https://user-images.githubusercontent.com/362174/69002560-cc1bf880-0945-11ea-9423-afbde8d7a1ba.png)

Same here in terms of memory.

**Comment by mbelang** [comment]
@estahn That is a lot of GBs for a small process :grimacing: I set the limit in ram to 128mb and let kube kill it periodically... This is not ideal. A real fix would be appreciated.

**Comment by golonzovsky** [comment]
we have unreasonable high write IO as well, which saturates node in GKE and causes iowait 

```
iotop -bon 1
Total DISK READ :       0.00 B/s | Total DISK WRITE :      21.26 M/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:      24.46 K/s
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
3369018 be/4 65535       0.00 B/s   21.26 M/s  0.00 % 50.82 % kubed run --v=3 --secure-port=8443 --audit-log-path=- --tls-cert-file=/var/serving-cert/tls.crt --tls-private-key-file=/var/serving-cert/tls.key --use-kubeapiserver-fqdn-for-aks=true --enable-analytics=true
```

its writing into `/tmp/indices/` per namespace. Unfortunately helm deployment doesent let to redefine scratch volume, so it all goes towards node io limit.

**Comment by tamalsaha** [comment]
Hi, I have released v0.12.0-rc.0 with a rewrite. Please try it and let me know if you are still seeing this issue. https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0

**Comment by mbelang** [comment]
@tamalsaha 

The new chart is breaking on EKS

```UPGRADE FAILED
Error: Chart requires kubernetesVersion: >=1.9.0 which is incompatible with Kubernetes v1.14.9-eks-c0eccc
Error: UPGRADE FAILED: Chart requires kubernetesVersion: >=1.9.0 which is incompatible with Kubernetes v1.14.9-eks-c0eccc
```

**Comment by tamalsaha** [comment]
> Error: Chart requires kubernetesVersion: >=1.9.0 which is incompatible with Kubernetes v1.14.9-eks-c0eccc
Error: UPGRADE FAILED: Chart requires kubernetesVersion: >=1.9.0 which is incompatible with Kubernetes v1.14.9-eks-c0eccc

Are you using Helm 2 or 3? This sounds like a Helm bug. As a workaround, I can remove this line https://github.com/appscode/kubed/blob/master/charts/kubed/Chart.yaml#L5

> events is forbidden: User "system:serviceaccount:kube-system:kubed-kubed" cannot create resource "events" in API group "" in the namespace "default"

If you add something like this to the kubed ClusterRole .

```
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
```

**Comment by mbelang** [comment]
@tamalsaha Helm2. didn't get time to uprade yet.

**Comment by tamalsaha** [comment]
I just released https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.1 . Can you try that?

**Comment by tamalsaha** [comment]
@mbelang , please try https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.2 . This adds the missing permission. Please let me know how that goes.

**Comment by mbelang** [comment]
All good so far @tamalsaha :+1:

**Comment by tamalsaha** [comment]
Thanks @mbelang ! Closing the issue.
